language: haskell
ghc:
  - "8.2.2"
  - "8.4.3"

sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  # - $HOME/.stack
  # - $HOME/haskell-ide-engine/.stack-work

addons:
  apt:
    packages:
    - npm

before_install:
  # Download and unpack the stack executable
  # - mkdir -p ~/.local/bin
  # - export PATH=$HOME/.local/bin:$PATH
  # - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    
  - cd $HOME
  # It's ok to fail
  - mkdir -p haskell-ide-engine
  - cd haskell-ide-engine
  - git init
  - git remote add origin https://github.com/Bubba/haskell-ide-engine.git
  - git pull origin heirarchal-document-symbols
  - git submodule init
  - git submodule sync
  - git submodule update
  - cabal new-configure
  - cabal new-build -j2
  # - export PATH=$HOME/haskell-ide-engine/dist-newstyle/build/*/ghc-*/haskell-ide-engine-*/x/hie/build:$PATH
  - cp `find dist-newstyle/ -name hie -type f | xargs -x ls -t | head -n1` $HOME/.cabal/bin/
  # - stack --no-terminal --skip-ghc-check install -j2
  # - stack exec hoogle generate
  - cabal install hoogle
  - hoogle generate
  - cd $TRAVIS_BUILD_DIR
  - npm update
  - npm i -g javascript-typescript-langserver

script:
  - cabal configure --enable-tests --enable-coverage
  - cabal build
  - cabal test --show-details=streaming
