language: c

sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - git clone https://github.com/Bubba/haskell-ide-engine.git --recursive
  - cd haskell-ide-engine
  - git checkout 377157dad7641c2c63e8b554a46a4888dca48721
  - stack --no-terminal --skip-ghc-check install -j1
  - stack exec hoogle generate
  - cd ..

script:
  - stack --no-terminal --skip-ghc-check test
