language: haskell
dist: xenial
ghc:
  - "8.6.5"
cabal: "2.4"

sudo: false

cache:
  directories:
    - $HOME/.cabal
    - $HOME/haskell-ide-engine/dist-newstyle
    # - .stack-work
    # - $HOME/.stack
    # - $HOME/haskell-ide-engine/.stack-work
  timeout: 1000

addons:
  apt:
    packages:
      - npm

before_install:
  # - mkdir -p ~/.local/bin
  # - export PATH=$HOME/.local/bin:$PATH
  # - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - mkdir -p haskell-ide-engine
  - cd $HOME/haskell-ide-engine
  - git init
  - git remote add origin https://github.com/haskell/haskell-ide-engine.git
  - git pull origin master
  - git checkout abdb097f39e135deaf321a604c95f16cbda32678
  - git submodule update --init
  - cabal v2-install hie
  # - stack --no-terminal --skip-ghc-check -j2 install --fast
  # - stack exec hoogle generate
  - cabal v2-run hoogle generate
  - cd $TRAVIS_BUILD_DIR
  - npm update
  - npm i -g javascript-typescript-langserver

script:
  - cabal v2-test
