language: haskell
ghc:
  - "8.2.2"
  - "8.4.3"

sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  # - $HOME/.stack
  - $HOME/haskell-ide-engine/dist
  - $HOME/haskell-ide-engine/dist-newstyle

addons:
  apt:
    packages:
    - npm
    - hoogle

before_install:
  - printenv
  # - cd $HOME
  - wget https://877-129435383-gh.circle-artifacts.com/0/bin/hie
  - export PATH=$TRAVIS_BUILD_DIR:$PATH
  # - mkdir -p haskell-ide-engine
  # - cd haskell-ide-engine
  # - git init
  # - git remote add origin https://github.com/Bubba/haskell-ide-engine.git
  # - git pull origin heirarchal-document-symbols
  # - git submodule init
  # - git submodule sync
  # - git submodule update
  # - cabal new-configure
  # - cabal new-build -j2
  # - export PATH=$HOME/haskell-ide-engine/dist-newstyle/build/*/ghc-*/haskell-ide-engine-*/c/hie/build/hie/hie:$PATH
  - npm update
  - npm i -g javascript-typescript-langserver

script:
  - cabal configure --enable-tests --enable-coverage
  - cabal build
  - hoogle generate
  - cabal test --show-details=streaming
after_script:
  - cabal install codecov-haskell --bindir=$TRAVIS_BUILD_DIR
  - ./codecov-haskell
