language: c

sudo: false

cache:
  directories:
    - .stack-work
    - $HOME/.stack
    - $HOME/haskell-ide-engine/.stack-work
  timeout: 1000

addons:
  apt:
    packages:
      - npm

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
  - mkdir -p haskell-ide-engine
  - cd $HOME/haskell-ide-engine
  - git init
  - git remote add origin https://github.com/haskell/haskell-ide-engine.git
  - git pull origin master
  - git checkout 47b5281d9d8ffe7348f7f7fcb3ce36b4eabd4f06
  - git submodule init
  - git submodule sync
  - git submodule update --init
  - stack --no-terminal --skip-ghc-check -j2 install
  - stack exec hoogle generate
  - cd $TRAVIS_BUILD_DIR
  - npm update
  - npm i -g javascript-typescript-langserver

script:
  - stack test
