# language: haskell
# ghc:
#   - "8.2.2"
#   - "8.4.2"
language: c

sudo: false

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack
  - $HOME/haskell-ide-engine/.stack-work

addons:
  apt:
    packages:
    - npm

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
    
  - cd $HOME
  # It's ok to fail
  - cd haskell-ide-engine
  - git init
  - git remote add origin https://github.com/haskell/haskell-ide-engine.git
  - git pull origin master
  - git submodule init
  - git submodule sync
  - git submodule update
  # - cabal new-update
  # - cabal new-configure
  # - cabal new-build
  # - export PATH=$HOME/haskell-ide-engine/dist-newstyle/build/*/ghc-*/haskell-ide-engine-*/x/hie/build:$PATH
  - stack --no-terminal --skip-ghc-check install -j2
  - stack exec hoogle generate
  - cd $TRAVIS_BUILD_DIR
  - npm update
  - npm i -g javascript-typescript-langserver

script:
 - stack test
  # - cabal configure --enable-tests
  # - cabal test -j2 --show-details=streaming
