resolver: nightly-2018-04-24
packages:
  - .

extra-deps:
  - github: Bubba/haskell-lsp-client
    commit: b7cf14eb48837a73032e867dab90db1708220c66
  - haskell-lsp-types-0.2.2.0
  - github: Bubba/haskell-lsp
    commit: d21ebcfbe8c2c09ac92e33fa18be0a2ce098b8bb
  - sorted-list-0.2.1.0
  - github: yi-editor/yi-rope
    commit: 7867909f4f20952be051fd4252cca5bbfc80cf41
