resolver: lts-13.24
packages:
  - .

extra-deps:
  - git: https://github.com/alanz/haskell-lsp.git
    commit: 491d8d2e33572b3868078f57a3375b2ac621f958
    subdirs:
      - .
      - haskell-lsp-types
  - rope-utf16-splay-0.3.1.0
