resolver: lts-13.26
packages:
  - .

extra-deps:
  - rope-utf16-splay-0.3.1.0
  - github: alanz/haskell-lsp
    commit: fefcae8b44aaf7658e0f90d5530832efe0b32053
    subdirs:
      - .
      - haskell-lsp-types
