resolver: nightly-2018-06-02
packages:
  - .

extra-deps:
  - github: Bubba/haskell-lsp-client
    commit: b7cf14eb48837a73032e867dab90db1708220c66
  - github: Bubba/haskell-lsp
    commit: 4c705c23cac58b4f6535474acc61d054230b6699
    subdirs:
      - .
      - ./haskell-lsp-types
  - sorted-list-0.2.1.0
  - github: yi-editor/yi-rope
    commit: 7867909f4f20952be051fd4252cca5bbfc80cf41
