resolver: nightly-2018-06-02
packages:
  - .

extra-deps:
  # - haskell-lsp
  - github: Bubba/haskell-lsp-client
    commit: b7cf14eb48837a73032e867dab90db1708220c66
  - github: Bubba/haskell-lsp
    commit: 3e046bf095568099dae606e1c20a92f1dc60b7b9
    subdirs:
      - .
      - ./haskell-lsp-types
  - sorted-list-0.2.1.0
  - github: yi-editor/yi-rope
    commit: 7867909f4f20952be051fd4252cca5bbfc80cf41
