name: Haskell CI

on: [push]

jobs:
  build:
   
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.6.5'
        cabal-version: '3.0'
    - run: cabal update
    - name: Install HIE
      run: |
        pushd $HOME
        git clone https://github.com/haskell/haskell-ide-engine --recurse-submodules
        cd haskell-ide-engine
        cabal install hie
        cabal install hoogle
        export PATH=$PATH:$HOME/.cabal/bin
        hoogle generate
        popd
    - name: Build
      run: cabal build
    - name: Run tests
      run: |
        export PATH=$PATH:$HOME/.cabal/bin
        echo $PATH
        which hie
        cabal test
