name: Haskell CI

on: [push, pull_request]
jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.10.1', '8.8.3', '8.6.5', '8.4.4']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        exclude:
          - os: windows-latest
            ghc: '8.8.3' # fails due to segfault

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1.1.4
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.2'

    - name: Cache Cabal
      uses: actions/cache@v1.2.0
      with:
        path: ~/.cabal
        key: ${{ runner.OS }}-${{ matrix.ghc }}-cabal-0

    - name: Build
      run: cabal build
    - name: Test
      run: cabal test
