name: Haskell CI

on: [push, pull_request]
jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        ghc: ['8.10.1', '8.8.3', '8.6.5', '8.4.4']
        os: [ubuntu-latest, macOS-latest, windows-latest]
        # exclude:
        #   - os: macOS-latest
        #     ghc: '8.4.4' # fails due to ghc panic

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-haskell@v1.1
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.0'
    - run: cabal update

    - name: Cache Cabal
      uses: actions/cache@v1.1.0
      with:
        path: ~/.cabal
        key: ${{ runner.OS }}-${{ matrix.ghc }}-cabal
        restore-keys: |
          ${{ runner.OS }}-${{ matrix.ghc }}-cabal

    - name: Build
      run: cabal build
    - name: Test
      run: cabal test
