name: Haskell CI

on: [push, pull_request]
jobs:
  build:
   
    runs-on: ${{ matrix.os }}

    env:
      hieref: 8582a960dc1ca389734707f821b273b00bae54ab

    strategy:
      matrix:
        ghc: ['8.6.5', '8.4.4']
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: bubba/setup-haskell@macos-ghcup
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.0'
    - run: cabal update

    - name: Clone HIE
      uses: actions/checkout@v1
      with:
        repository: haskell/haskell-ide-engine
        submodules: recursive
        ref: ${{ env.hieref }}
        path: haskell-ide-engine

    # - name: Cache Cabal
    #   uses: actions/cache@v1
    #   with:
    #     path: ~/.cabal
    #     key: ${{ runner.OS }}-${{ matrix.ghc }}-cabal-${{ hashFiles('../**/*.cabal') }}
    #     restore-keys: |
    #       ${{ runner.OS }}-${{ matrix.ghc }}-cabal

    - name: Build HIE
      run: |
        # if [ -e $HOME/.cabal/bin/hie ]; then
        #     echo "hie is already built"
        #     exit 0
        # fi
        pushd ../haskell-ide-engine
        cabal install hie
        cabal install hoogle
        hoogle generate
        popd
    - name: Install JS Language Server
      run: npm install javascript-typescript-langserver
    - name: Build
      run: cabal build
    - name: Test
      run: |
        echo $PATH
        echo $(npm bin)
        export PATH=$PATH:$(npm bin) 
        cabal test
