name: Haskell CI

on: [push]
jobs:
  build:
   
    runs-on: ${{ matrix.os }}

    env:
      hieref: 52691a63087ceb585c8bdc2ea04b52df3b2eddf1

    strategy:
      matrix:
        ghc: ['8.6.5']
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: bubba/setup-haskell@macos-ghcup
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.0'
    - run: cabal update

    - name: Clone HIE
      uses: actions/checkout@v1
      with:
        repository: mpickering/haskell-ide-engine
        submodules: recursive
        ref: ${{ env.hieref }}
        path: haskell-ide-engine

    - name: Cache Cabal
      uses: actions/cache@v1
      with:
        path: ~/.cabal
        key: ${{ runner.OS }}-${{ matrix.ghc }}-cabal

    - name: Build HIE
      run: |
        # if [ -e $HOME/.cabal/bin/hie ]; then
        #     echo "hie is already built"
        #     exit 0
        # fi
        pushd ../haskell-ide-engine
        cabal install hie
        cabal install hoogle
        hoogle generate
        popd
        cabal v1-install Cabal --constraint "Cabal == 3.0.0.0"
    - name: Install JS Language Server
      run: npm install javascript-typescript-langserver
    - name: Build
      run: cabal build
    # - name: Test
    #   run: |
    #     echo $PATH
    #     export PATH=$PATH:$(npm bin) 
    #     cabal run lsp-test:test:tests
