name: Haskell CI

on: [push]
jobs:
  build:
   
    runs-on: ${{ matrix.os }}

    env:
      hieref: 7cf1295a2804a527381331bb7b73d58255721edc

    strategy:
      matrix:
        ghc: ['8.6.5']
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - uses: bubba/setup-haskell@macos-ghcup
      with:
        ghc-version: ${{ matrix.ghc }}
        cabal-version: '3.0'
    - run: cabal update

    - name: Clone HIE
      uses: actions/checkout@v1
      with:
        repository: haskell/haskell-ide-engine
        submodules: recursive
        ref: ${{ env.hieref }}
        path: haskell-ide-engine

    - name: Cache HIE
      uses: actions/cache@v1
      with:
        path: haskell-ide-engine/dist-newstyle
        key: ${{ runner.OS }}-${{ matrix.ghc }}-${{ env.hieref }}

    - name: Build HIE
      run: |
        # if [ -e $HOME/.cabal/bin/hie ]; then
        #     echo "hie is already built"
        #     exit 0
        # fi
        pushd ../haskell-ide-engine
        cabal install hie
        cabal install hoogle
        hoogle generate
        popd
        cabal v1-install Cabal --constraint "Cabal == 3.0.0.0"
    - name: Install JS Language Server
      run: npm install javascript-typescript-langserver
    - name: Build
      run: cabal build
    - name: Test
      run: |
        export PATH=$PATH:$HOME/.cabal/bin:$(npm bin) 
        cabal run lsp-test:test:tests
